import path from 'node:path';
import type { AppConfig } from '../apps/api/src/infrastructure/config';

export function createScriptAppConfig(overrides: Partial<AppConfig> = {}): AppConfig {
  const config = {
    dataDir: path.resolve('.tmp/script-app-config-data'),
    openapiYamlPath: path.resolve('packages/openapi/skill-registry.openapi.yaml'),
    registryId: 'script-check-registry',
    registryName: 'Script Check Registry',
    publicApiBaseUrl: 'https://script-check.example.com/api',
    corsAllowedOrigins: [],
    adminCsrfOriginCheck: false,
    adminUiBasePath: '/frontend/admin',
    apiHost: '127.0.0.1',
    apiPort: 3040,
    apiTrustedProxies: [],
    adminAuthMode: 'simple',
    adminUser: 'admin',
    adminPassword: 'admin',
    adminPasswordHash: '',
    jwtSecret: 'script-check-secret',
    sessionTtlSeconds: 3600,
    adminLoginRateLimitWindowMs: 300_000,
    adminLoginRateLimitMaxRequests: 10,
    adminLoginRateLimitMaxBuckets: 10_000,
    judgerProvider: 'noop',
    judgerAdapterPath: null,
    vercelAiSdkModel: null,
    vercelAiSdkTimeoutMs: 30_000,
    vercelAiSdkMaxTextChars: 12_000,
    vercelAiSdkMaxRetries: 0,
    catalogProvider: 'sqlite',
    searchProvider: 'sqlite',
    contentStorageProvider: 'filesystem',
    mysqlHost: '127.0.0.1',
    mysqlPort: 3306,
    mysqlDatabase: 'managed_skill_hub',
    mysqlUser: 'managed_skill_hub',
    mysqlPassword: '',
    mysqlSslMode: 'preferred',
    mysqlConnectTimeoutMs: 10_000,
    mysqlQueryTimeoutMs: 30_000,
    proposalMaxFiles: 30,
    proposalMaxFileSizeBytes: 10 * 1024 * 1024,
    proposalDisallowedPaths: ['node_modules/', '.venv/', 'venv/'],
    proposalRateLimitWindowMs: 60_000,
    proposalRateLimitMaxRequests: 120,
    proposalRateLimitMaxBuckets: 10_000,
    allowOpenProposalsInProduction: false,
    autoPublishOnGreen: false,
    autoPublishExcludedCategories: ['security', 'automation', 'filesystem', 'network'],
    autoPublishSimilarityThreshold: 0.5,
    autoApproveWithoutJudger: false,
    publishJudgementPolicy: 'disabled',
    publicReadAuthMode: 'none',
    publicReadBearerToken: null,
    publicReadBearerActor: 'read-agent',
    proposalAuthMode: 'none',
    proposalBearerToken: null,
    proposalBearerActor: 'proposal-agent',
    discoveryAuthMode: 'none',
    discoveryBearerToken: null,
    discoveryBearerActor: 'discovery-agent',
    oidcAgentIssuer: null,
    oidcAgentClientId: null,
    oidcAgentBaseScopes: ['openid', 'profile', 'email'],
    oidcDiscoveryScope: null,
    oidcPublicReadScope: null,
    oidcProposalScope: null,
    oidcAdminIssuer: null,
    oidcAdminClientId: null,
    oidcAdminClientSecret: null,
    oidcAdminRedirectUri: null,
    oidcAdminScopes: ['openid', 'profile', 'email'],
    oidcProposalAccess: 'all_authenticated_users',
    oidcProposalGroups: ['managedskillhub-submitters'],
    oidcPublicReadAccess: 'all_authenticated_users',
    oidcPublicReadGroups: ['managedskillhub-readers'],
    oidcAdminSubjects: [],
    oidcAdminGroups: ['managedskillhub-admins'],
    oidcReviewerGroups: ['managedskillhub-reviewers'],
    oidcPublisherGroups: ['managedskillhub-publishers'],
    oidcLoginTransactionTtlSeconds: 600,
    oidcClockToleranceSeconds: 30,
    oidcJwksCacheTtlSeconds: 3600,
    oidcHttpTimeoutMs: 5000,
    oidcMaxTokenBytes: 16_384,
    oidcMaxGroups: 100,
    oidcHumanClaim: 'managedskillhub_human',
    oidcAccessTokenValidationMode: 'jwt_profile',
    oidcIntrospectionClientId: null,
    oidcIntrospectionClientSecret: null,
    agentSessionEnabled: false,
    agentSessionTtlSeconds: 3 * 3600,
    agentSessionCodeLength: 8,
    agentSessionCodeCharset: 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789',
    agentSessionMaxActive: 10,
    agentSessionAuthRateLimitWindowMs: 60_000,
    agentSessionAuthRateLimitMaxFailures: 30,
    agentSessionAuthRateLimitMaxBuckets: 10_000,
    ...overrides,
  } satisfies AppConfig;

  return config;
}
