import { CatalogMigration } from './catalog-migration';

/** Frozen transitional baseline for installations that predate migration history. */
export const migration: CatalogMigration = {
  id: '2026082600_baseline_legacy_catalog',
  description: 'Baseline the legacy catalog schema before versioned migrations.',
  async up(context) {
    await context.executeSchema(context.provider === 'sqlite' ? SQLITE_LEGACY_SCHEMA : MYSQL_LEGACY_SCHEMA);
  },
};

// Snapshot of the pre-migration catalog. Never edit this SQL; append a new
// migration instead. It deliberately excludes judgement reuse columns.
const SQLITE_LEGACY_SCHEMA = `
CREATE TABLE IF NOT EXISTS skill_catalog_versions (skill_id TEXT NOT NULL,version TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL,category TEXT NOT NULL,tags TEXT NOT NULL,capabilities TEXT NOT NULL,use_when TEXT NOT NULL,do_not_use_when TEXT NOT NULL,entrypoint TEXT NOT NULL,status TEXT NOT NULL,skill_uuid TEXT NOT NULL,version_uuid TEXT NOT NULL,content_digest TEXT NOT NULL,created_at TEXT NOT NULL,approved_by TEXT,approved_at TEXT,published_by TEXT,published_at TEXT,rejected_by TEXT,rejected_at TEXT,rejection_reason TEXT,deprecated_by TEXT,deprecated_at TEXT,deprecation_reason TEXT,updated_at TEXT,is_latest_published INTEGER NOT NULL DEFAULT 0,is_latest_version INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(skill_id,version));
CREATE TABLE IF NOT EXISTS skill_catalog_files (skill_id TEXT NOT NULL,version TEXT NOT NULL,path TEXT NOT NULL,artifact_id TEXT NOT NULL,role TEXT NOT NULL,mime_type TEXT NOT NULL,size_bytes INTEGER NOT NULL,sha256 TEXT,updated_at TEXT,extractable INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(skill_id,version,path));
CREATE TABLE IF NOT EXISTS skill_catalog_judgements (id TEXT PRIMARY KEY,target_type TEXT NOT NULL,target_id TEXT NOT NULL,proposal_id TEXT,skill_id TEXT,skill_version TEXT,dimensions TEXT NOT NULL,overall_risk TEXT NOT NULL,summary TEXT NOT NULL,skill_purpose_summary TEXT,model TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS skill_catalog_proposals (id TEXT PRIMARY KEY,skill_id TEXT,title TEXT NOT NULL,description TEXT NOT NULL,category TEXT NOT NULL,tags TEXT NOT NULL,capabilities TEXT NOT NULL,entrypoint TEXT,status TEXT NOT NULL,submitted_by TEXT NOT NULL,submitted_by_principal_id TEXT,submitted_via_client_id TEXT,created_at TEXT NOT NULL,rejection_reason TEXT,latest_judgement_risk TEXT,review_labels TEXT NOT NULL DEFAULT '[]',latest_judgement_id TEXT,latest_judged_at TEXT,content_digest TEXT);
CREATE TABLE IF NOT EXISTS skill_catalog_proposal_files (proposal_id TEXT NOT NULL,id TEXT NOT NULL,path TEXT NOT NULL,mime_type TEXT NOT NULL,size_bytes INTEGER NOT NULL,sha256 TEXT,PRIMARY KEY(proposal_id,path));
CREATE TABLE IF NOT EXISTS skill_catalog_audit_entries (id TEXT PRIMARY KEY,skill_id TEXT,skill_version TEXT,proposal_id TEXT,action TEXT NOT NULL,actor TEXT NOT NULL,actor_principal_id TEXT,actor_display_name TEXT,actor_client_id TEXT,before_json TEXT,after_json TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS identity_principals (id TEXT PRIMARY KEY,kind TEXT NOT NULL,display_name TEXT,email TEXT,first_seen_at TEXT NOT NULL,last_seen_at TEXT NOT NULL,disabled_at TEXT);
CREATE TABLE IF NOT EXISTS identity_external_subjects (issuer TEXT NOT NULL,external_subject TEXT NOT NULL,principal_id TEXT NOT NULL,provider_client_id TEXT NOT NULL,first_seen_at TEXT NOT NULL,last_seen_at TEXT NOT NULL,PRIMARY KEY(issuer,external_subject));
CREATE TABLE IF NOT EXISTS admin_sessions (session_id_hash TEXT PRIMARY KEY,principal_id TEXT NOT NULL,roles_json TEXT NOT NULL,created_at TEXT NOT NULL,last_seen_at TEXT NOT NULL,expires_at TEXT NOT NULL,revoked_at TEXT,revoked_reason TEXT);
CREATE TABLE IF NOT EXISTS agent_sessions (session_id TEXT NOT NULL,code TEXT PRIMARY KEY,areas TEXT NOT NULL,created_at TEXT NOT NULL,expires_at TEXT NOT NULL,revoked_at TEXT,last_used_at TEXT,created_by_ip TEXT,last_used_ip TEXT,user_agent TEXT);
CREATE TABLE IF NOT EXISTS oidc_login_transactions (state_hash TEXT PRIMARY KEY,nonce TEXT NOT NULL,pkce_verifier TEXT NOT NULL,redirect_uri TEXT NOT NULL,return_path TEXT NOT NULL,created_at TEXT NOT NULL,expires_at TEXT NOT NULL,consumed_at TEXT);
`;

const MYSQL_LEGACY_SCHEMA = `
CREATE TABLE IF NOT EXISTS skill_catalog_versions (skill_id VARCHAR(255) NOT NULL,version VARCHAR(64) NOT NULL,title VARCHAR(1024) NOT NULL,description TEXT NOT NULL,category VARCHAR(255) NOT NULL,capabilities JSON NOT NULL,use_when JSON NOT NULL,do_not_use_when JSON NOT NULL,entrypoint VARCHAR(1024) NOT NULL,status VARCHAR(32) NOT NULL,skill_uuid CHAR(36) NOT NULL,version_uuid CHAR(36) NOT NULL,content_digest CHAR(64) NOT NULL,created_at DATETIME NOT NULL,approved_by VARCHAR(255),approved_at DATETIME,published_by VARCHAR(255),published_at DATETIME,rejected_by VARCHAR(255),rejected_at DATETIME,rejection_reason TEXT,deprecated_by VARCHAR(255),deprecated_at DATETIME,deprecation_reason TEXT,updated_at DATETIME,is_latest_published TINYINT(1) NOT NULL DEFAULT 0,is_latest_version TINYINT(1) NOT NULL DEFAULT 0,PRIMARY KEY(skill_id,version)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS skill_catalog_version_tags (skill_id VARCHAR(255) NOT NULL,version VARCHAR(64) NOT NULL,tag VARCHAR(255) NOT NULL,PRIMARY KEY(skill_id,version,tag),KEY idx_skill_catalog_tags_tag(tag,skill_id,version),CONSTRAINT fk_version_tags FOREIGN KEY(skill_id,version) REFERENCES skill_catalog_versions(skill_id,version) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS skill_catalog_files (skill_id VARCHAR(255) NOT NULL,version VARCHAR(64) NOT NULL,path VARCHAR(255) NOT NULL,artifact_id CHAR(36) NOT NULL,role VARCHAR(64) NOT NULL,mime_type VARCHAR(255) NOT NULL,size_bytes BIGINT NOT NULL,sha256 CHAR(64),updated_at DATETIME,extractable TINYINT(1) NOT NULL DEFAULT 0,PRIMARY KEY(skill_id,version,path),KEY idx_skill_catalog_files_version(skill_id,version),CONSTRAINT fk_skill_files FOREIGN KEY(skill_id,version) REFERENCES skill_catalog_versions(skill_id,version) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS skill_catalog_judgements (id CHAR(36) PRIMARY KEY,target_type VARCHAR(32) NOT NULL,target_id VARCHAR(255) NOT NULL,proposal_id VARCHAR(64),skill_id VARCHAR(255),skill_version VARCHAR(64),dimensions JSON NOT NULL,overall_risk VARCHAR(32) NOT NULL,summary TEXT NOT NULL,skill_purpose_summary TEXT,model VARCHAR(255),created_at DATETIME NOT NULL,KEY idx_skill_catalog_judgements_target(target_type,target_id,created_at),KEY idx_skill_catalog_judgements_proposal(proposal_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS skill_catalog_proposals (id VARCHAR(64) PRIMARY KEY,skill_id VARCHAR(255),title VARCHAR(255) NOT NULL,description TEXT NOT NULL,category VARCHAR(255) NOT NULL,tags JSON NOT NULL,capabilities JSON NOT NULL,entrypoint VARCHAR(1024),status VARCHAR(32) NOT NULL,submitted_by VARCHAR(255) NOT NULL,submitted_by_principal_id CHAR(36),submitted_via_client_id VARCHAR(512),created_at DATETIME NOT NULL,rejection_reason TEXT,latest_judgement_risk VARCHAR(32),review_labels JSON NOT NULL DEFAULT (JSON_ARRAY()),latest_judgement_id CHAR(36),latest_judged_at DATETIME,content_digest CHAR(64),KEY idx_skill_catalog_proposals_status(status,created_at),KEY idx_skill_catalog_proposals_skill(skill_id,created_at),KEY idx_skill_catalog_proposals_content_digest(content_digest)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS skill_catalog_proposal_files (proposal_id VARCHAR(64) NOT NULL,id VARCHAR(255) NOT NULL,path VARCHAR(255) NOT NULL,mime_type VARCHAR(255) NOT NULL,size_bytes BIGINT NOT NULL,sha256 CHAR(64),PRIMARY KEY(proposal_id,path),KEY idx_skill_catalog_proposal_files(proposal_id,path),CONSTRAINT fk_proposal_files FOREIGN KEY(proposal_id) REFERENCES skill_catalog_proposals(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS skill_catalog_audit_entries (id CHAR(36) PRIMARY KEY,skill_id VARCHAR(255),skill_version VARCHAR(64),proposal_id VARCHAR(64),action VARCHAR(255) NOT NULL,actor VARCHAR(255) NOT NULL,actor_principal_id CHAR(36),actor_display_name VARCHAR(512),actor_client_id VARCHAR(512),before_json JSON,after_json JSON,created_at DATETIME NOT NULL,KEY idx_skill_catalog_audit_skill(skill_id,created_at),KEY idx_skill_catalog_audit_proposal(proposal_id,created_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS identity_principals (id CHAR(36) PRIMARY KEY,kind VARCHAR(32) NOT NULL,display_name VARCHAR(512),email VARCHAR(512),first_seen_at DATETIME(3) NOT NULL,last_seen_at DATETIME(3) NOT NULL,disabled_at DATETIME(3),KEY idx_identity_principals_last_seen(last_seen_at,id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS identity_external_subjects (issuer VARCHAR(1024) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,external_subject VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,principal_id CHAR(36) NOT NULL,provider_client_id VARCHAR(512) NOT NULL,first_seen_at DATETIME(3) NOT NULL,last_seen_at DATETIME(3) NOT NULL,UNIQUE KEY uq_identity_external_subject(issuer,external_subject),KEY idx_identity_external_principal(principal_id),CONSTRAINT fk_identity_external_principal FOREIGN KEY(principal_id) REFERENCES identity_principals(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS admin_sessions (session_id_hash CHAR(64) PRIMARY KEY,principal_id CHAR(36) NOT NULL,roles_json JSON NOT NULL,created_at DATETIME(3) NOT NULL,last_seen_at DATETIME(3) NOT NULL,expires_at DATETIME(3) NOT NULL,revoked_at DATETIME(3),revoked_reason VARCHAR(512),KEY idx_admin_sessions_expiry(expires_at,session_id_hash),CONSTRAINT fk_admin_session_principal FOREIGN KEY(principal_id) REFERENCES identity_principals(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS agent_sessions (session_id CHAR(36) NOT NULL,code VARCHAR(32) PRIMARY KEY,areas JSON NOT NULL,created_at DATETIME(3) NOT NULL,expires_at DATETIME(3) NOT NULL,revoked_at DATETIME(3),last_used_at DATETIME(3),created_by_ip VARCHAR(64),last_used_ip VARCHAR(64),user_agent TEXT,UNIQUE KEY uq_agent_sessions_session_id(session_id),KEY idx_agent_sessions_expiry(expires_at,code),KEY idx_agent_sessions_revoked(revoked_at,code)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS oidc_login_transactions (state_hash CHAR(64) PRIMARY KEY,nonce VARCHAR(512) NOT NULL,pkce_verifier VARCHAR(512) NOT NULL,redirect_uri VARCHAR(2048) NOT NULL,return_path VARCHAR(1024) NOT NULL,created_at DATETIME(3) NOT NULL,expires_at DATETIME(3) NOT NULL,consumed_at DATETIME(3),KEY idx_oidc_login_transactions_expiry(expires_at,state_hash)) ENGINE=InnoDB;`;
