import type { Knex } from 'knex';
import { CatalogMigration, CatalogMigrationContext } from './catalog-migration';

/** Knex owns migration state and locking; this source owns immutable provider DDL. */
export class CatalogKnexMigrationSource implements Knex.MigrationSource<CatalogMigration> {
  constructor(private readonly provider: 'sqlite' | 'mysql', private readonly migrations: readonly CatalogMigration[]) {}
  getMigrations(_loadExtensions: readonly string[]): Promise<CatalogMigration[]> { return Promise.resolve([...this.migrations]); }
  getMigrationName(migration: CatalogMigration): string { return migration.id; }
  async getMigration(migration: CatalogMigration): Promise<Knex.Migration> {
    const knexMigration = { up: async (knex: Knex) => migration.up(context(this.provider, knex)), down: async () => { throw new Error(`Catalog migrations are forward-only: ${migration.id}`); } };
    (knexMigration as Knex.Migration & { config?: { transaction: boolean } }).config = { transaction: this.provider === 'sqlite' };
    return knexMigration;
  }
}
function context(provider: 'sqlite' | 'mysql', knex: Knex): CatalogMigrationContext {
  return { provider,
    executeSchema: async (sql) => { for (const statement of sql.split(';').map((item) => item.trim()).filter(Boolean)) await knex.raw(statement); },
    addColumnIfMissing: async (table, column, definition) => { if (!(await knex.schema.hasColumn(table, column))) await knex.raw(`ALTER TABLE ${id(table)} ADD COLUMN ${id(column)} ${definition}`); },
    addIndexIfMissing: async (table, index, columns, unique = false) => {
      if (provider === 'sqlite') { const indexes = await knex.raw(`PRAGMA index_list(${id(table)})`) as unknown as Array<{ name: string; unique: number }>; const current = indexes.find((item) => item.name === index); const currentColumns = current ? (await knex.raw(`PRAGMA index_info(${id(index)})`) as unknown as Array<{ name: string }>).map((item) => item.name) : []; if (current && (Boolean(current.unique) !== unique || currentColumns.join(',') !== columns.join(','))) await knex.raw(`DROP INDEX ${id(index)}`); if (!current || Boolean(current.unique) !== unique || currentColumns.join(',') !== columns.join(',')) await knex.raw(`CREATE ${unique ? 'UNIQUE ' : ''}INDEX ${id(index)} ON ${id(table)} (${columns.map(id).join(', ')})`); return; }
      const rows = await knex('information_schema.statistics').select('column_name', 'non_unique').where({ table_schema: knex.client.config.connection.database, table_name: table, index_name: index }).orderBy('seq_in_index') as Array<{ column_name: string; non_unique: number }>;
      const actualColumns = rows.map((row) => row.column_name); const matches = rows.length > 0 && Number(rows[0].non_unique) === (unique ? 0 : 1) && actualColumns.join(',') === columns.join(','); if (matches) return;
      const foreignKeyRows = await knex('information_schema.key_column_usage as k').join('information_schema.referential_constraints as r', function () { this.on('r.constraint_schema', '=', 'k.constraint_schema').andOn('r.constraint_name', '=', 'k.constraint_name').andOn('r.table_name', '=', 'k.table_name'); }).select({ constraint_name: 'k.constraint_name', column_name: 'k.column_name', referenced_table_name: 'k.referenced_table_name', referenced_column_name: 'k.referenced_column_name', delete_rule: 'r.delete_rule' }).where({ 'k.constraint_schema': knex.client.config.connection.database, 'k.table_name': table }).whereNotNull('k.referenced_table_name').orderBy(['k.constraint_name', 'k.ordinal_position']) as Array<{ constraint_name: string; column_name: string; referenced_table_name: string; referenced_column_name: string; delete_rule: 'CASCADE' | 'RESTRICT' }>;
      const foreignKeys = new Map<string, { columns: string[]; parent: string; parentColumns: string[]; deleteRule: 'CASCADE' | 'RESTRICT' }>(); for (const row of foreignKeyRows) { const foreignKey = foreignKeys.get(row.constraint_name) ?? { columns: [], parent: row.referenced_table_name, parentColumns: [], deleteRule: row.delete_rule }; foreignKey.columns.push(row.column_name); foreignKey.parentColumns.push(row.referenced_column_name); foreignKeys.set(row.constraint_name, foreignKey); }
      const dependent = [...foreignKeys.entries()].filter(([, foreignKey]) => actualColumns.slice(0, foreignKey.columns.length).join(',') === foreignKey.columns.join(',') || columns.slice(0, foreignKey.columns.length).join(',') === foreignKey.columns.join(',')); for (const [constraint] of dependent) await knex.raw(`ALTER TABLE ${id(table)} DROP FOREIGN KEY ${id(constraint)}`); if (rows.length) await knex.raw(`DROP INDEX ${id(index)} ON ${id(table)}`); await knex.raw(`CREATE ${unique ? 'UNIQUE ' : ''}INDEX ${id(index)} ON ${id(table)} (${columns.map(id).join(', ')})`); for (const [constraint, foreignKey] of dependent) await knex.raw(`ALTER TABLE ${id(table)} ADD CONSTRAINT ${id(constraint)} FOREIGN KEY (${foreignKey.columns.map(id).join(', ')}) REFERENCES ${id(foreignKey.parent)} (${foreignKey.parentColumns.map(id).join(', ')}) ON DELETE ${foreignKey.deleteRule}`);
    },
    addForeignKeyIfMissing: async (table, constraint, columns, referencedTable, referencedColumns, onDelete) => { if (provider === 'sqlite') return; const rows = await knex('information_schema.key_column_usage as k').join('information_schema.referential_constraints as r', function () { this.on('r.constraint_schema', '=', 'k.constraint_schema').andOn('r.constraint_name', '=', 'k.constraint_name').andOn('r.table_name', '=', 'k.table_name'); }).select({ constraint_name: 'k.constraint_name', column_name: 'k.column_name', referenced_table_name: 'k.referenced_table_name', referenced_column_name: 'k.referenced_column_name', delete_rule: 'r.delete_rule' }).where({ 'k.constraint_schema': knex.client.config.connection.database, 'k.table_name': table }).orderBy(['k.constraint_name', 'k.ordinal_position']) as Array<{ constraint_name: string; column_name: string; referenced_table_name: string; referenced_column_name: string; delete_rule: 'CASCADE' | 'RESTRICT' }>; const foreignKeys = new Map<string, { columns: string[]; parent: string; parentColumns: string[]; deleteRule: 'CASCADE' | 'RESTRICT' }>(); for (const row of rows) { const foreignKey = foreignKeys.get(row.constraint_name) ?? { columns: [], parent: row.referenced_table_name, parentColumns: [], deleteRule: row.delete_rule }; foreignKey.columns.push(row.column_name); foreignKey.parentColumns.push(row.referenced_column_name); foreignKeys.set(row.constraint_name, foreignKey); } const sameRelationship = [...foreignKeys.entries()].filter(([, foreignKey]) => foreignKey.columns.join(',') === columns.join(',') && foreignKey.parent === referencedTable && foreignKey.parentColumns.join(',') === referencedColumns.join(',')); const canonical = foreignKeys.get(constraint); const canonicalMatches = canonical?.columns.join(',') === columns.join(',') && canonical.parent === referencedTable && canonical.parentColumns.join(',') === referencedColumns.join(',') && canonical.deleteRule === onDelete; if (canonicalMatches && sameRelationship.length === 1) return; const toDrop = new Set(sameRelationship.map(([name]) => name)); if (canonical) toDrop.add(constraint); for (const name of toDrop) await knex.raw(`ALTER TABLE ${id(table)} DROP FOREIGN KEY ${id(name)}`); await knex.raw(`ALTER TABLE ${id(table)} ADD CONSTRAINT ${id(constraint)} FOREIGN KEY (${columns.map(id).join(', ')}) REFERENCES ${id(referencedTable)} (${referencedColumns.map(id).join(', ')}) ON DELETE ${onDelete}`); },
  };
}
function id(value: string): string { if (!/^[a-z_][a-z0-9_]*$/.test(value)) throw new Error(`Unsafe migration identifier: ${value}`); return value; }
