import { execFile } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { existsSync, mkdirSync } from 'node:fs';
import { link, open, readFile, rename, unlink } from 'node:fs/promises';
import path from 'node:path';
import knexFactory, { Knex } from 'knex';
import { AppConfig, loadConfig } from '../config';
import { MysqlClient } from '../../adapters/outbound/mysql/mysql.connection';
import { CatalogMigration } from './catalog-migration';
import { CatalogKnexMigrationSource } from './knex-migration-source';
import { catalogMigrations } from './migrations';

const LEGACY_TABLE = 'managed_skill_hub_schema_migrations'; const KNEX_TABLE = 'knex_migrations';
export interface CatalogMigrationPlan { provider: 'sqlite' | 'mysql'; pendingMigrationIds: string[]; requiresBackup: boolean; }
interface CatalogMigrationRunOptions { beforeApply?: (plan: CatalogMigrationPlan) => Promise<void>; }
export async function planCatalogMigrations(config: AppConfig, migrations: readonly CatalogMigration[] = catalogMigrations): Promise<CatalogMigrationPlan> { if (config.catalogProvider === 'sqlite' && !existsSync(sqliteDatabasePath(config))) return { provider: 'sqlite', pendingMigrationIds: migrations.map((migration) => migration.id), requiresBackup: false }; const knex = createKnex(config, migrations, true); try { return await readPlan(knex, config, migrations); } finally { await knex.destroy(); } }
export async function runCatalogMigrations(config: AppConfig, migrations: readonly CatalogMigration[] = catalogMigrations, options: CatalogMigrationRunOptions = {}): Promise<string[]> { const knex = createKnex(config, migrations); try { return await withCutoverLock(config, async () => { await options.beforeApply?.(await readPlan(knex, config, migrations)); await adoptLegacyState(knex, config, migrations); const currentPlan = await readPlan(knex, config, migrations); if (!currentPlan.pendingMigrationIds.length) return []; const [, completed] = await knex.migrate.latest(optionsFor(config, migrations)); return completed; }); } finally { await knex.destroy(); } }
export async function migrateCatalogWithBackup(config: AppConfig): Promise<string[]> { return runCatalogMigrations(config, catalogMigrations, { beforeApply: async (currentPlan) => { if (currentPlan.requiresBackup) await backup(currentPlan.provider === 'mysql' ? 'scripts/operations/backup-mysql-for-migration.sh' : 'scripts/operations/backup.sh', config); } }); }
function sqliteDatabasePath(config: AppConfig): string { return path.join(config.dataDir, 'index', 'search.db'); }
function createKnex(config: AppConfig, migrations: readonly CatalogMigration[], readOnly = false): Knex { if (config.catalogProvider === 'sqlite') { const filename = sqliteDatabasePath(config); if (!readOnly) mkdirSync(path.dirname(filename), { recursive: true }); return knexFactory({ client: 'better-sqlite3', connection: { filename, readonly: readOnly } as never, useNullAsDefault: true, migrations: optionsFor(config, migrations), log: safeKnexLogger() }); } return knexFactory({ client: 'mysql2', connection: { host: config.mysqlHost, port: config.mysqlPort, user: config.mysqlUser, password: config.mysqlPassword, database: config.mysqlDatabase, timezone: 'Z', ssl: mysqlSsl(config.mysqlSslMode) }, migrations: optionsFor(config, migrations), log: safeKnexLogger() }); }
function safeKnexLogger(): Knex.Config['log'] { return { warn: () => undefined, error: () => undefined, deprecate: () => undefined, debug: () => undefined }; }
function optionsFor(config: AppConfig, migrations: readonly CatalogMigration[]): Knex.MigratorConfig { return { tableName: KNEX_TABLE, migrationSource: new CatalogKnexMigrationSource(config.catalogProvider, migrations) }; }
async function readPlan(knex: Knex, config: AppConfig, migrations: readonly CatalogMigration[]): Promise<CatalogMigrationPlan> { const stateTable = await knex.schema.hasTable(KNEX_TABLE) ? KNEX_TABLE : (await knex.schema.hasTable(LEGACY_TABLE) ? LEGACY_TABLE : null); const applied = stateTable ? new Set((await knex<{ id?: string; name?: string }>(stateTable).select(stateTable === KNEX_TABLE ? 'name' : 'id')).map((row) => row.name ?? row.id)) : new Set<string>(); const pendingMigrationIds = migrations.filter((migration) => !applied.has(migration.id)).map((migration) => migration.id); return { provider: config.catalogProvider, pendingMigrationIds, requiresBackup: pendingMigrationIds.length > 0 && await knex.schema.hasTable('skill_catalog_versions') }; }
async function adoptLegacyState(knex: Knex, config: AppConfig, migrations: readonly CatalogMigration[]): Promise<void> { await knex.migrate.list(optionsFor(config, migrations)); const state = await knex(KNEX_TABLE).count<{ count: number | string }>({ count: '*' }).first(); if (Number(state?.count ?? 0) > 0) return; const known = new Set(migrations.map((migration) => migration.id)); const rows = await knex.schema.hasTable(LEGACY_TABLE) ? await knex<{ id: string }>(LEGACY_TABLE).select('id') : []; const names = rows.map((row) => row.id).filter((id) => known.has(id)); if (names.length) await knex(KNEX_TABLE).insert(names.map((name) => ({ name, batch: 0, migration_time: new Date() }))); }
async function withCutoverLock<T>(config: AppConfig, action: () => Promise<T>): Promise<T> { if (config.catalogProvider === 'mysql') { const client = new MysqlClient(config); try { return await client.withConnection(async (connection) => { const [rows] = await connection.query<{ acquired: number | string }>("SELECT GET_LOCK('managed-skill-hub-schema-migrations', 30) AS acquired"); if (String(rows[0]?.acquired) !== '1') throw new Error('Timed out while waiting for catalog migration cutover lock.'); try { return await action(); } finally { await connection.query("SELECT RELEASE_LOCK('managed-skill-hub-schema-migrations')"); } }); } finally { await client.close(); } } const lockPath = path.join(config.dataDir, 'index', '.knex-migration-cutover.lock'); const handle = await acquireSqliteCutoverLock(lockPath); try { return await action(); } finally { await handle.close(); await unlink(lockPath).catch(() => undefined); } }
async function acquireSqliteCutoverLock(lockPath: string) { const deadline = Date.now() + 30_000; while (true) { const candidatePath = `${lockPath}.candidate-${process.pid}-${randomUUID()}`; try { const candidate = await open(candidatePath, 'wx'); await candidate.writeFile(JSON.stringify({ pid: process.pid, processStart: await processStartIdentity(process.pid), acquiredAt: new Date().toISOString() })); await candidate.sync(); await candidate.close(); await link(candidatePath, lockPath); const handle = await open(lockPath, 'r+'); await unlink(candidatePath).catch(() => undefined); return handle; } catch (error) { await unlink(candidatePath).catch(() => undefined); if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error; if (await removeStaleSqliteCutoverLock(lockPath)) continue; if (Date.now() >= deadline) throw new Error('Timed out while waiting for catalog migration cutover lock.'); await new Promise((resolve) => setTimeout(resolve, 100)); } } }
async function removeStaleSqliteCutoverLock(lockPath: string): Promise<boolean> { let owner: { pid?: unknown; processStart?: unknown }; try { owner = JSON.parse(await readFile(lockPath, 'utf8')) as { pid?: unknown; processStart?: unknown }; } catch { owner = {}; } if (Number.isInteger(owner.pid) && (owner.pid as number) > 0) { const currentProcessStart = await processStartIdentity(owner.pid as number); if (typeof owner.processStart === 'string' && currentProcessStart === owner.processStart) return false; if (currentProcessStart !== null && typeof owner.processStart !== 'string') return false; if (currentProcessStart === null) try { process.kill(owner.pid as number, 0); return false; } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ESRCH') return false; } } const tombstonePath = `${lockPath}.stale-${process.pid}-${randomUUID()}`; try { await rename(lockPath, tombstonePath); } catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return false; throw error; } await unlink(tombstonePath).catch(() => undefined); return true; }
async function processStartIdentity(pid: number): Promise<string | null> { return new Promise((resolve) => execFile('ps', ['-o', 'lstart=', '-p', String(pid)], (error, stdout) => { const identity = stdout.trim(); resolve(error || !identity ? null : identity); })); }
function mysqlSsl(mode: AppConfig['mysqlSslMode']): false | { rejectUnauthorized: boolean } | undefined { if (mode === 'disabled') return false; return mode === 'required' || mode === 'verify_ca' || mode === 'verify_identity' ? { rejectUnauthorized: true } : undefined; }
async function backup(script: string, config: AppConfig): Promise<void> { await new Promise<void>((resolve, reject) => execFile('bash', [script], { cwd: process.cwd(), env: { ...process.env, DATA_DIR: config.dataDir, CATALOG_PROVIDER: config.catalogProvider, CONTENT_STORAGE_PROVIDER: config.contentStorageProvider, MYSQL_HOST: config.mysqlHost, MYSQL_PORT: String(config.mysqlPort), MYSQL_DATABASE: config.mysqlDatabase, MYSQL_USER: config.mysqlUser, MYSQL_PASSWORD: config.mysqlPassword, MYSQL_SSL_MODE: config.mysqlSslMode } }, (error) => error ? reject(new Error('Pre-migration backup failed.')) : resolve())); }
async function main(): Promise<void> { const config = loadConfig(); if (process.argv.includes('--plan')) { console.log(JSON.stringify(await planCatalogMigrations(config))); return; } const completed = await migrateCatalogWithBackup(config); console.log(completed.length ? `Applied catalog schema migrations: ${completed.join(', ')}` : 'Catalog schema migrations are already current.'); }
if (require.main === module) main().catch(() => { console.error('Catalog schema migration failed. Check controlled deployment diagnostics.'); process.exitCode = 1; });
